from strategies.monolithic import MonolithicStrategy
from strategies.iterative import IterativeStrategy 
from strategies.hierarchical import HierarchicalStrategy
from strategies.incremental import IncrementalStrategy
from strategies.bottom import BottomUpStrategy